### ISSUE TITLE
Subtitles freezing 

### ISSUE THREAD

**Issue by JD-Alx** [vocably/vocably-pro#5]
After installing the extensions, my subtitles on YouTube started freezing if I do alt-tab (00:07 on my vid), until I refresh the window or until I press alt twice (00:25). And strangely, I don't have to press alt like those instructions say to make the pop-up appear. If I press alt, the pop-up is highlighted, but in a crooked way - I can't highlight the combination of words I need, it just disappears or highlights everything, or something random....

https://github.com/vocably/vocably-pro/assets/159651224/efabadd0-5401-427b-94a5-d938de68eee7

**Comment by sneas** [comment]
Hey mate, thank you for creating the issue and making the video! It is super helpful. I have seen your review on the Chrome Web Store.

I'll check it out on a Windows machine soon.

**Comment by sneas** [comment]
Hi, I've just published a new version of the extension to the Google Chrome Web Store. I hope it will be verified by Google and released soon.

I expect that after the release, the youtube functionality to work stably on Windows and you can proceed with your style of watching.

But honestly, the text selection with the Alt key in YouTube is not perfect and requires more work. I plan to invest some time in it in the upcoming weeks.

Thanks again for opening the issue and making the video! You helped this project a great deal.

**Comment by sneas** [comment]
The Chrome extension version 1.233.1 has been released. Let me know if you have any problem with it.

**Comment by JD-Alx** [comment]
Thank you for such quick feedback ^_^

**Comment by JD-Alx** [comment]
Omg, looks like everything is working perfectly now :D Thanks :)

**Comment by sneas** [comment]
Thanks a lot for helping out with that! It wouldn't be solved without your help.

And thanks for the 5-star review, it means a lot to me and to the project.
